model_name: "/data2/huggingface-mirror/dataroot/models/meta-llama/Llama-2-7b-chat-hf"
watermark_name: "Unigram" 
watermark_path: "/home/lsz/MarkText/watermark/Unigram_watermark"
output_path: "/data1/lzs/MarkText"
prompt_path: "/data1/lzs/MarkText/prompts"
#trainin setting
batch_size: 1
temperature: 1.0
devices: [2]